"""initial tables

Revision ID: 02c12ea250a6
Revises: a86ca8d244eb
Create Date: 2026-02-04 20:32:05.565586

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '02c12ea250a6'
down_revision: Union[str, None] = 'a86ca8d244eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
