"""create_all_tables

Revision ID: a86ca8d244eb
Revises: 
Create Date: 2026-02-04 20:30:45.832577

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a86ca8d244eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'INVIGILATOR', 'STUDENT', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_role', 'users', ['email', 'role'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('question_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qbank_subject_active', 'question_banks', ['subject', 'is_active'], unique=False)
    op.create_index(op.f('ix_question_banks_id'), 'question_banks', ['id'], unique=False)
    op.create_index(op.f('ix_question_banks_subject'), 'question_banks', ['subject'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('question_bank_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='examstatusenum'), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('show_result_immediately', sa.Boolean(), nullable=False),
    sa.Column('allow_review', sa.Boolean(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('difficulty_distribution', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='check_duration_positive'),
    sa.CheckConstraint('end_time > start_time', name='check_end_after_start'),
    sa.CheckConstraint('passing_marks <= total_marks', name='check_passing_marks'),
    sa.CheckConstraint('total_questions > 0', name='check_total_questions_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exam_bank_status', 'exams', ['question_bank_id', 'status'], unique=False)
    op.create_index('ix_exam_status_time', 'exams', ['status', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_index(op.f('ix_exams_question_bank_id'), 'exams', ['question_bank_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'TRUE_FALSE', 'FILL_BLANK', name='questiontypeenum'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultyenum'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('negative_marks', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('marks >= 0', name='check_marks_positive'),
    sa.CheckConstraint('negative_marks >= 0', name='check_negative_marks_positive'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_active_bank', 'questions', ['is_active', 'question_bank_id'], unique=False)
    op.create_index('ix_question_bank_type_diff', 'questions', ['question_bank_id', 'question_type', 'difficulty'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_question_bank_id'), 'questions', ['question_bank_id'], unique=False)
    op.create_table('exam_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_student_assignment')
    )
    op.create_index('ix_assignment_student', 'exam_assignments', ['student_id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_id'), 'exam_assignments', ['id'], unique=False)
    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('students_started', sa.Integer(), nullable=False),
    sa.Column('students_submitted', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sessions_id'), 'exam_sessions', ['id'], unique=False)
    op.create_index('ix_session_exam_active', 'exam_sessions', ['exam_id', 'is_active'], unique=False)
    op.create_table('student_exam_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('paper_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'AUTO_SUBMITTED', 'EVALUATED', name='paperstatusenum'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', 'attempt_number', name='uq_student_exam_attempt')
    )
    op.create_index('ix_paper_status', 'student_exam_papers', ['status'], unique=False)
    op.create_index('ix_paper_student_exam', 'student_exam_papers', ['student_id', 'exam_id'], unique=False)
    op.create_index(op.f('ix_student_exam_papers_id'), 'student_exam_papers', ['id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('category_wise_score', sa.JSON(), nullable=True),
    sa.Column('difficulty_wise_score', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['student_exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', 'paper_id', name='uq_exam_student_result')
    )
    op.create_index('ix_result_exam_rank', 'results', ['exam_id', 'rank'], unique=False)
    op.create_index('ix_result_student', 'results', ['student_id'], unique=False)
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_table('session_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('flagged_by', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flag_session_student', 'session_flags', ['session_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_session_flags_id'), 'session_flags', ['id'], unique=False)
    op.create_table('student_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=500), nullable=True),
    sa.Column('is_marked_for_review', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['student_exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'question_id', name='uq_paper_question_response')
    )
    op.create_index('ix_response_paper', 'student_responses', ['paper_id'], unique=False)
    op.create_index('ix_response_question', 'student_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_responses_id'), 'student_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_responses_id'), table_name='student_responses')
    op.drop_index('ix_response_question', table_name='student_responses')
    op.drop_index('ix_response_paper', table_name='student_responses')
    op.drop_table('student_responses')
    op.drop_index(op.f('ix_session_flags_id'), table_name='session_flags')
    op.drop_index('ix_flag_session_student', table_name='session_flags')
    op.drop_table('session_flags')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_index('ix_result_student', table_name='results')
    op.drop_index('ix_result_exam_rank', table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_student_exam_papers_id'), table_name='student_exam_papers')
    op.drop_index('ix_paper_student_exam', table_name='student_exam_papers')
    op.drop_index('ix_paper_status', table_name='student_exam_papers')
    op.drop_table('student_exam_papers')
    op.drop_index('ix_session_exam_active', table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_index(op.f('ix_exam_assignments_id'), table_name='exam_assignments')
    op.drop_index('ix_assignment_student', table_name='exam_assignments')
    op.drop_table('exam_assignments')
    op.drop_index(op.f('ix_questions_question_bank_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index('ix_question_bank_type_diff', table_name='questions')
    op.drop_index('ix_question_active_bank', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exams_question_bank_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_index('ix_exam_status_time', table_name='exams')
    op.drop_index('ix_exam_bank_status', table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_question_banks_subject'), table_name='question_banks')
    op.drop_index(op.f('ix_question_banks_id'), table_name='question_banks')
    op.drop_index('ix_qbank_subject_active', table_name='question_banks')
    op.drop_table('question_banks')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_role', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
